# Generated by Django 4.1.1 on 2022-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("project", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=9)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=9)),
                ("dollars", models.DecimalField(decimal_places=2, max_digits=9)),
                ("record_date", models.DateField()),
            ],
        ),
    ]
