# Generated by Django 4.1.1 on 2022-09-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectdata",
            old_name="project",
            new_name="project_name",
        ),
    ]
